config/routes.rb
Rails.application.routes.draw do
  root'home#index'
  resources :login, only: [:new, :create]
  delete "logout", to: "login#destroy", as: "log_out"
  resources :reviews
  resources :animes
  resources :home, only: [:index, :show ]
  resources :users


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/anime.rb
class Anime < ApplicationRecord
  has_many :reviews
  has_many :users, through: :reviews 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/login.rb
class Login < ApplicationRecord



end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :anime
  validates :stars,  numericality: { only_integer: true, less_than_or_equal_to: 5 }
end

app/models/user.rb
class User < ApplicationRecord

  has_secure_password

  has_many :reviews
  has_many :animes, through: :reviews

validates :email, presence: true, uniqueness: true
validates :name, presence: true


end

app/controllers/animes_controller.rb
class AnimesController < ApplicationController
  before_action :set_anime, only: [:show, :edit, :new, :update, :destroy]

  def index
    @animes = Anime.all
  end

  def new
    @anime = Anime.new
  end

  def create
    @anime = Anime.new(anime_params)

    respond_to do |format|
      if @anime.save
        format.html { redirect_to @anime, notice: 'Anime was successfully created.' }
        format.json { render :show, status: :created, location: @anime }
      else
        format.html { render :new }
        format.json { render json: @anime.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @anime.update(anime_params)
        format.html { redirect_to @anime, notice: 'Anime was successfully updated.' }
        format.json { render :show, status: :ok, location: @anime }
      else
        format.html { render :edit }
        format.json { render json: @anime.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @anime.destroy
    respond_to do |format|
      format.html { redirect_to animes_url, notice: 'Anime was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_anime
      @anime = Anime.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def anime_params
      params.require(:anime).permit(:title, :episode, :season, :summary, :img_url)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  skip_before_action :verify_authenticity_token

  before_action :setup
  before_action :current_user

  def current_user
    @user = (User.find_by(id: session[:user_id])|| User.new)
  end

  def get_notification
    flash["message"]
  end

  def set_notification(message)
    flash["message"] = message
  end

  private

  def log_in_user(user_id)
  session[:user_id] = user_id
  end

  def log_out_user
    session[:user_id] = nil
  end

  def setup

    @logged_in = !!session[:user_id]
    if @logged_in
      @logged_in_user_id = session[:user_id]
      @logged_in_user = User.find(@logged_in_user_id)
      # @remaining_votes = @logged_in_user.remaining_votes
      # @can_vote = @logged_in_user.can_vote
    end

    @notification = get_notification
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :current_user

  def index
    @anime = Anime.all
    @user = current_user
  end
end

app/controllers/login_controller.rb
class LoginController < ApplicationController

  def new
   @errors = flash[:errors]
  end

  def create
   @user = User.find_by(email: params[:email])
   if @user && @user.authenticate(params[:password])
     log_in_user(@user.id)
     redirect_to root_path
   else
     flash[:errors] = [ "User doesn't exist or invalid password" ]
     redirect_to new_login_path
   end
  end

  def destroy
   log_out_user
   redirect_to root_path
  end

end

app/controllers/logins_controller.rb
class LoginsController < ApplicationController
 
  def new
   @errors = flash[:errors]
  end

  def create
   @user = User.find_by(username: params[:username])
   if @user && @user.authenticate(params[:password])
     log_in_user(@user.id)
     redirect_to anime_path
   else
     flash[:errors] = [ "User doesn't exist or invalid password" ]
     redirect_to new_login_path
   end
  end

  def destroy
   log_out_user
   redirect_to login_path
  end


end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: [:show, :edit, :update, :destroy]

  def index
    @reviews = Review.all
  end


    def create
      unless @logged_in
        set_notification("You're not logged in ")
        redirect_to new_login_path
        return
      end

      if @can_vote
        # use_one_vote
        @vote = Vote.create(color_id: params[:color_id], user_id: session[:user_id])
        # byebug
      else
        set_notification("You're out of votes 🖕")
      end
      redirect_to colors_path
    end

    def destroy
      @vote = Vote.find(params[:id])
      if @vote.user_id == @logged_in_user_id
        @vote.destroy
      end
      redirect_to votes_path
    end
  def new
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)

    respond_to do |format|
      if @review.save
        format.html { redirect_to @review, notice: 'Review was successfully created.' }
        format.json { render :show, status: :created, location: @review }
      else
        format.html { render :new }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @review.update(review_params)
        format.html { redirect_to @review, notice: 'Review was successfully updated.' }
        format.json { render :show, status: :ok, location: @review }
      else
        format.html { render :edit }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @review.destroy
    respond_to do |format|
      format.html { redirect_to reviews_url, notice: 'Review was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_review
      @review = Review.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def review_params
      params.require(:review).permit(:stars, :user_id, :anime_id, :comment)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :set_user, only: [:show, :edit, :update, :destroy]
  # before_action :require_login


  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.create(user_params)

    if @user.valid?
      log_in_user(@user.id)
      redirect_to root_path
    else
      @errors = @user.errors.full_messages
      render :new
    end
  end


  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end


  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
end

app/helpers/animes_helper.rb
module AnimesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/logins_helper.rb
module LoginsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/animes/_form.html.erb
<%= form_with(model: anime, local: true) do |form| %>
  <% if anime.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(anime.errors.count, "error") %> prohibited this anime from being saved:</h2>

      <ul>
      <% anime.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :episode %>
    <%= form.text_field :episode %>
  </div>

  <div class="field">
    <%= form.label :season %>
    <%= form.number_field :season %>
  </div>

  <div class="field">
    <%= form.label :summary %>
    <%= form.text_field :summary %>
  </div>

  <div class="field">
    <%= form.label :img_url %>
    <%= form.text_field :img_url %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/animes/new.html.erb
<h1>New Anime</h1>

<%= render 'form', anime: @anime %>

<%= link_to 'Back', animes_path %>

app/views/animes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @anime.title %>
</p>

<p>
  <strong>Episode:</strong>
  <%= @anime.episode %>
</p>

<p>
  <strong>Season:</strong>
  <%= @anime.season %>
</p>

<p>
  <strong>Summary:</strong>
  <%= @anime.summary %>
</p>

<h3><%= link_to 'New Review', new_review_path %></h3>


<%= link_to 'Back', home_path %>

app/views/home/index.html.erb
<p id=”notice”><%= notice %></p>
<h1 class="header">Welcome to ANI</h1>
<div class="user_welcome">
  <h2>Welcome<%= link_to @user.name, user_path(@user) %></h2>
</div>
<div class="button">
<%= button_to "Log out", log_out_path, method: :delete %>
</div>
<hr>
<div class="logs">
  <%= link_to "Log-In", new_login_path %>
  <%= link_to "Sign-Up", new_user_path %>
</div>

<br>

<iframe width="600" height="480" src="https://www.youtube.com/embed/tqqusEyL76M" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
<div class="feature">
<h3 id="pop">Popular anime</h3>
  <ol>
    <li></li>
  </ol>
</div>
<hr>
<h2 id="list">List of anime</h2>
<ol>
  <% @anime.each do |ani| %>
  <li>
    <img src=<%= ani.img_url %>>
    <h4><%= link_to ani.title, ani %></h4>
    <p><%= ani.summary %></p>

   </li>
  <% end %>
</ol>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ANI</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% @page_title = "UserAuth | Signup" %>

    <%= yield %>
  </body>
</html>

app/views/login/_form.html.erb
<ol class="errors">
  <% @user.errors.full_messages.each do |message| %>
    <li>
      <%= message %>
    </li>
  <% end %>
</ol>

<%= form_for @user do |f| %>

  <ul>
    <li>
      <%= f.label :email %>
      <%= f.text_field :email %>
    </li>
    <li>
      <%= f.label :password_digest %>
      <%= f.password_field :password_digest %>
    </li>
  </ul>

  <%= f.submit %>

<% end %>

app/views/login/new.html.erb
<%= form_tag login_index_path do %>
   <ul>
    <li>
      <%= label_tag :email %>
      <%= text_field_tag :email %>
    </li>
    <li>
      <%= label_tag :password %>
      <%= password_field_tag :password %>
    </li>
  </ul>
  <%= submit_tag%>
<% end %>

app/views/reviews/_form.html.erb
<%= form_with(model: review, local: true) do |form| %>
  <% if review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(review.errors.count, "error") %> prohibited this review from being saved:</h2>

      <ul>
      <% review.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :stars %>
    <%= form.number_field :stars %>
  </div>


  <div class="field">
    <%= form.label :comment %>
    <%= form.text_field :comment %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/reviews/edit.html.erb
<h1>Editing Review</h1>

<%= render 'form', review: @review %>

<%= link_to 'Show', @review %> |
<%= link_to 'Back', reviews_path %>

app/views/reviews/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Reviews</h1>

<table>
  <thead>
    <tr>
      <th>Stars</th>
      <th>User</th>
      <th>Anime</th>
      <th>Comment</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reviews.each do |review| %>
      <tr>
        <td><%= review.stars %></td>
        <td><%= review.user_id %></td>
        <td><%= review.anime_id %></td>
        <td><%= review.comment %></td>
        <td><%= link_to 'Show', review %></td>
        <td><%= link_to 'Edit', edit_review_path(review) %></td>
        <td><%= link_to 'Destroy', review, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Review', new_review_path %>

app/views/reviews/new.html.erb
<h1>New Review</h1>

<%= render 'form', review: @review %>

<%= link_to 'Back', reviews_path %>

app/views/reviews/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Stars:</strong>
  <%= @review.stars %>
</p>

<p>
  <strong>User:</strong>
  <%= @review.user_id %>
</p>

<p>
  <strong>Anime:</strong>
  <%= @review.anime_id %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @review.comment %>
</p>

<%= link_to 'Edit', edit_review_path(@review) %> |
<%= link_to 'Back', reviews_path %>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>

  <div class="field">
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', home_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', root_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <h2><strong>Name:</strong></h2>
  <%= @user.name %>
</p>

<p>
    <h2><strong>Email:</strong></h2>
  <%= @user.email %>
</p>

<p>
  <strong>Reviews:</strong>
  <ul>
      <% @user.reviews.each do |review| %>
    <li>
      <%= link_to review.comment, review %>
      <%= button_to "Edit Comment", edit_review_path %>
      <%= button_to "Delete Comment", destroy_review_path %>
    </li>
  </ul>
  <% end %>

</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', root_path %>